spring.application.name=student-api

# Server
server.port=8080

# root level applies to everything unless overridden below
logging.level.root=INFO

# our own application code ? see more detail during development
logging.level.com.mentor.student-api=DEBUG

# quiet down noisy framework internals
logging.level.org.hibernate=WARN
logging.level.org.springframework.web=WARN

# log file output location
logging.file.name=logs/student-api.log

# PostgreSQL connection

spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=postgres
spring.datasource.password=Rajesh@22
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.hibernate.SQL=debug
